#!/usr/bin/env python3
"""Schlafparalyse V5 render entrypoint.

Uses the shared NOESIS renderer but forces the episode-specific V5 visual cue
sheets generated by prepare_schlafparalyse_visuals_v5.py.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools import noesis_render as nr  # noqa: E402

for ep in ("EP06", "EP07", "EP08"):
    nr.PROFILES[ep]["cue"] = "VISUAL_CUE_SHEET_V5.csv"

if __name__ == "__main__":
    raise SystemExit(nr.main())
